### ISSUE TITLE
[Bug]: @everyone role does not work for whitelisting

### ISSUE THREAD

**Issue by kaydenvg** [Awakened-Redstone/AutoWhitelist#24]
### Version information

1.0.0 Alpha 8

### Version type

Full

### Expected Behavior

users with no role/`@everyone` are able to use np!register to whitelist themselves

### Actual Behavior

"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Reproduction Steps

1. Be a normal `@everyone` user
2. Type np!register <username> 
3. response is:
"Sorry, but I couldn't accept your request
It seems that you don't have the required subscription/member level or don't have your Twitch/Youtube account linked to your Discord account."

### Java version

N/A, issue with bot

### Additional information

Whitelisting self works with any role other than the default `@everyone`. Made a new role with no special permissions/not admin and it works, but I'd prefer if anyone joining the server with the default role could whitelist themselves.

**Comment by Awakened-Redstone** [comment]
Yeah, it shouldn't be complicated. I have been pretty busy recently, so I haven't had time to work on the issue. I'll try working on it this weekend.

**Comment by csm-kb** [comment]
I ask because we'd be happy to make the change and make the PR, given which way you want to take it! 🙇‍♂️

**Comment by Awakened-Redstone** [comment]
You are always free to make a PR

**Comment by csm-kb** [comment]
Would the config option be the preferred method here?

**Comment by Awakened-Redstone** [comment]
I have considered adding a small additional line for processing `@everyone` (from server id) into a role for the cached list or process something like id -1 into the role, the reason I don't look for the presence of the role or add an option for that is because I want to allow the users to also use roles along `@everyone`

I want to later work on some QoL for the mod and push it into beta or release when I have more time, feel free to make a PR with a workaround, it can be improved later, the mod is currently on alpha state.

**Comment by Awakened-Redstone** [comment]
Fixed by #27, patch released in [1.0.0-alpha.10](https://modrinth.com/mod/autowhitelist/version/1.0.0-alpha.10)
